# Generated by Django 3.2.15 on 2024-12-09 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('Car_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Is_leased', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('Model', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.repository')),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.repository')),
                ('Model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_model', to='management.vehicle')),
            ],
        ),
    ]
